feta: avatar features, bgCOlor, and border Radius
web3ui/web3uikit pull request #230
Opened 2022-03-08 14:14 UTC by rayyan224

<img width="1059" alt="Screen Shot 2022-03-08 at 9 14 37 AM" src="https://user-images.githubusercontent.com/62478924/157255206-55e09152-3ecd-4f9e-8f0d-1d8ea9d890ef.png">

2022-03-08 15:52 UTC, BillyG83 requested changes

2022-03-08 18:32 UTC, Y0moo commented
@rayyan224 nice job! Could you please also add props for font-size and size(width=height)

2022-03-09 09:54 UTC, locothedev commented on src/components/Avatar/types.ts
> +     * Avatar Background, if not specified we will generate random color
GENIUSSSSS !!!!! ❤️

2022-03-09 15:07 UTC, rayyan224 commented on src/components/Avatar/Avatar.tsx
> +            borderRadius={borderRadius}
lol, one day Bill, one-day... imma do it automatically.
Imma make u proud just u wait ✊

2022-03-09 15:47 UTC, locothedev approved these changes

2022-03-09 15:47 UTC, merged