feat: New Button theme: text
web3ui/web3uikit pull request #450
Opened 2022-04-14 10:04 UTC by niklabh

![Screenshot from 2022-04-14 12-02-51](https://user-images.githubusercontent.com/874046/163362952-e4161d75-5059-4018-950e-50ca8cdb8158.png)

![Screenshot from 2022-04-14 12-03-03](https://user-images.githubusercontent.com/874046/163362951-1c922d5e-d8f1-4293-bb92-d8f364ed5a76.png)

![Screenshot from 2022-04-14 12-03-21](https://user-images.githubusercontent.com/874046/163362948-4c5ca153-6d4e-4c5c-80a4-454b6cf41c9d.png)

2022-04-14 14:32 UTC, Y0moo requested changes

2022-04-14 14:32 UTC, Y0moo commented on src/components/Button/styles/standardThemes.ts
> +    background-color: ${color.white};
Let's replace it to `transparent` here

2022-04-14 14:32 UTC, Y0moo commented on src/components/Button/styles/standardThemes.ts
> +    :active {
Following the style in Figma, we need to have a "gray" bg in active state

![image](https://user-images.githubusercontent.com/78314301/163412486-0404eac8-c7c3-470f-8174-d5e2d6976d29.png)

2022-04-14 14:34 UTC, Y0moo commented on src/components/Button/styles/standardThemes.ts
> +        background-color: ${color.blueLight};
Should be there `background-color: ${color.blueSkyDark};`

2022-04-14 14:35 UTC, Y0moo commented
Great work @niklabh, please check my comments

2022-04-15 06:48 UTC, niklabh commented
Done

2022-04-18 11:54 UTC, BillyG83 requested changes
nit sure this works, it looks like `secondary` when i use `text`

what is the required result? Just text but acts like a button? Maybe it would need less padding also to sit inline with text?

2022-04-18 11:54 UTC, BillyG83 commented
![Screenshot 2022-04-18 at 13 52 12](https://user-images.githubusercontent.com/13779759/163804613-eaff43b0-7ef3-4a91-90e7-e5189d392504.png)

from my testing

2022-04-19 13:39 UTC, Y0moo commented
weird, why do you have themes as a string input and not as a group of radios in the canvas? It should be like: 

![image](https://user-images.githubusercontent.com/78314301/164016791-9b80e8c1-7da6-4693-a703-ee23fd6341c5.png)

2022-04-19 14:00 UTC, niklabh commented
> weird, why do you have themes as a string input and not as a group of radios in the canvas? It should be like:
> 
> ![image](https://user-images.githubusercontent.com/78314301/164016791-9b80e8c1-7da6-4693-a703-ee23fd6341c5.png)

Strange. No idea why its happening

2022-04-22 07:45 UTC, BillyG83 commented
> why do you have themes as a string input and not as a group of radios in the canvas? It should be like:

i think once you have too many options Storybook shows the dropdown instead of radios to save space

2022-04-27 19:52 UTC, closed without merging